import {products,stores,matchProduct,referencePrice,totalCents} from './demo-core.mjs';
const content=document.querySelector('#demo-content');
const status=document.querySelector('#demo-status');
const money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(n);
let view='search',selected=products[0],cart=[],recipe=false;
function announce(text){status.textContent=text;}
function offer(p,i){return `<article class="offer"><img class="product-photo" src="assets/products/${p.id}.png" width="80" height="80" alt="Unbranded ${p.name.toLowerCase()} illustration" loading="lazy" /><div class="offer-description"><h4>${p.name==='Eggs'?'Large Brown Eggs':p.name==='Milk'?'Whole Milk':'Fresh Chicken'}</h4><p class="store">${stores[i]}</p><p class="spec">${p.spec}</p></div><div class="offer-bottom"><div><div class="price">${money(p.prices[i])}</div><span class="unit-price">${money(p.prices[i]/p.amount)} / ${p.unit}</span></div><button class="primary-btn" data-add="${p.id}" data-store="${i}" aria-label="Add ${p.name.toLowerCase()} from ${stores[i]} to demo list">+ Add to List</button></div></article>`;}
function syncTotals(){document.querySelector('#list-count').textContent=cart.reduce((s,r)=>s+r.quantity,0);document.querySelector('#app-total-value').textContent=money(totalCents(cart)/100);}
function reference(p){const units=p.unit==='kg'?['kg','lb']:p.unit==='L'?['L','mL']:['each'];return `<details class="reference"><summary>Reference <span class="reference-tag">Demo average</span></summary><p>Illustrative average: ${money(p.reference)} / ${p.referenceAmount} ${p.unit}. Demo calculation only; this is not a current StatCan or BLS observation.</p><div class="quantity-row"><div class="quantity-field"><label for="reference-quantity">Quantity</label><input id="reference-quantity" type="number" min="${p.unit==='each'?'1':'0.000001'}" max="1000000" step="${p.unit==='each'?'1':'any'}" value="${p.amount}" inputmode="${p.unit==='each'?'numeric':'decimal'}" /></div><div class="quantity-field"><label for="reference-unit">Unit</label><select id="reference-unit">${units.map(u=>`<option>${u}</option>`).join('')}</select></div></div><output id="reference-result" aria-live="polite"></output><p>The app shows the source, region and data month for supported statistical references. A reference is not a store’s regular price.</p></details>`;}
function render(){
 document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));
 syncTotals();
 if(view==='search'){
 content.innerHTML=`<div class="app-page-heading"><h3>Search Items</h3><p>Find your groceries. Compare your options.</p></div><div class="search-panel"><form class="search-form"><div class="field"><label for="demo-query">Search groceries</label><input id="demo-query" type="search" placeholder="Try eggs, milk or chicken" autocomplete="off" value="${selected?selected.name:''}" /></div><button class="primary-btn" type="submit">Search</button></form><div class="chips">${products.map(p=>`<button type="button" class="chip" data-product="${p.id}" aria-pressed="${selected?.id===p.id}">${p.name}</button>`).join('')}</div></div>${selected?`<div class="result-heading"><h3>${selected.name.toLowerCase()}</h3><p>3 demo offers</p></div><div class="offers">${stores.map((_,i)=>offer(selected,i)).join('')}</div>${reference(selected)}`:'<p class="empty-state">This small demo includes eggs, milk and chicken. Choose one above to compare example offers.</p>'}<div class="example-recipe"><strong>From a meal idea to a shopping list</strong><p>Try a fixed recipe example: “Chicken omelette for two.” The app supports AI ingredient search; this website shows a prepared example.</p><button class="secondary" data-recipe>${recipe?'Hide':'Show'} example ingredients</button>${recipe?'<p>Example ingredients; this is not a complete recipe.</p><div class="recipe-ingredients"><span>Eggs</span><span>Milk</span><span>Chicken</span></div><p>We’ll add one example offer for each ingredient. Adjust the shopping quantities in My list.</p><button class="primary-btn" data-add-recipe>Add ingredients to list</button>':''}</div>`;
 updateReference();
 }else if(view==='flyers'){
 content.innerHTML=`<div class="result-heading"><h3>Local Store Flyers</h3><p>Demo Market A · CAD</p></div><p class="list-note">Fictional flyer examples, with no live retailer content.</p><div class="offers">${products.map(p=>offer(p,0)).join('')}</div><button class="secondary" data-go-search>Compare prices across demo stores →</button>`;
 }else{
 content.innerHTML=`<div class="result-heading"><h3>Shopping List</h3><button class="secondary" data-clear>Reset list</button></div>${cart.length?cart.map((r,i)=>{const p=products.find(p=>p.id===r.product);return `<div class="list-row"><div><h4>${p.name}</h4><p>${stores[r.store]} · ${p.spec}</p><p>${money(p.prices[r.store])} ${p.unit==='kg'?'per kg':'per pack'}</p></div><div class="list-controls"><button data-adjust="${i}" data-delta="-1" aria-label="Decrease ${p.name} quantity">−</button><span aria-label="${p.name} quantity">${r.quantity}${p.unit==='kg'?' kg':''}</span><button data-adjust="${i}" data-delta="1" aria-label="Increase ${p.name} quantity">+</button><strong>${money(p.prices[r.store]*r.quantity)}</strong><button class="remove" data-remove="${i}" aria-label="Remove ${p.name} from ${stores[r.store]}">Remove</button></div></div>`;}).join(''):'<p class="empty-state">Your list is empty. Add an example offer from Flyers or Search to start planning.</p><button class="primary-btn" data-go-search>Find groceries</button>'}<div class="list-total"><span>Estimated total</span><span>${money(totalCents(cart)/100)}</span></div><p class="list-note">Example prices in CAD, before taxes. This demo list stays on this page and resets when you reload.</p>`;
 }
}
function updateReference(){if(!selected)return;const q=document.querySelector('#reference-quantity'),u=document.querySelector('#reference-unit'),out=document.querySelector('#reference-result');if(!q||!u||!out)return;const n=referencePrice(selected,q.value,u.value);out.textContent=n===null?`Enter a positive ${selected.unit==='each'?'whole ':''}number up to 1,000,000.`:`Estimated reference: ${money(n)} for ${q.value} ${u.value}`;q.setAttribute('aria-invalid',String(n===null));}
function add(product,store){let row=cart.find(r=>r.product===product&&r.store===store);if(row){if(row.quantity>=99)return false;row.quantity++;}else cart.push({product,store,quantity:1});return true;}
document.querySelector('#open-demo-list').addEventListener('click',()=>{view='list';render();document.querySelector('.app-scroll').scrollTop=0;announce('');});
document.querySelector('.demo-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){view=b.dataset.view;announce('');render();document.querySelector('.app-scroll').scrollTop=0;}});
content.addEventListener('submit',e=>{e.preventDefault();const value=document.querySelector('#demo-query').value;selected=matchProduct(value);render();announce(selected?`Showing three example offers for ${selected.name.toLowerCase()}.`:'No matching demo product. Try eggs, milk or chicken.');document.querySelector('#demo-query').focus();});
content.addEventListener('input',e=>{if(e.target.id==='reference-quantity')updateReference();});
content.addEventListener('change',e=>{if(e.target.id==='reference-unit')updateReference();});
content.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.product){selected=products.find(p=>p.id===b.dataset.product);render();content.querySelector(`[data-product="${selected.id}"]`).focus();announce(`Showing ${selected.name.toLowerCase()} offers.`);}
 else if(b.dataset.add){const ok=add(b.dataset.add,Number(b.dataset.store));syncTotals();announce(ok?`${products.find(p=>p.id===b.dataset.add).name} added. Open My list to adjust quantities.`:'Demo limit: 99 per item.');}
 else if(b.hasAttribute('data-go-search')){view='search';render();document.querySelector('#demo-query').focus();announce('');}
 else if(b.hasAttribute('data-recipe')){recipe=!recipe;render();content.querySelector('[data-recipe]').focus();}
 else if(b.hasAttribute('data-add-recipe')){products.forEach(p=>add(p.id,0));view='list';render();announce('Three example ingredients added to your list.');}
 else if(b.hasAttribute('data-clear')){cart=[];render();content.querySelector('[data-clear]').focus();announce('Demo list reset.');}
 else if(b.hasAttribute('data-remove')){cart.splice(Number(b.dataset.remove),1);render();content.querySelector('[data-clear]').focus();announce('Item removed.');}
 else if(b.hasAttribute('data-adjust')){const i=Number(b.dataset.adjust),delta=Number(b.dataset.delta);cart[i].quantity=Math.max(1,Math.min(99,cart[i].quantity+delta));render();content.querySelector(`[data-adjust="${i}"][data-delta="${delta}"]`).focus();announce('Quantity and total updated.');}
});
render();
